version: '3.8'

services:
  eopf-zarr-driver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jupyter/work/data:ro
      - ./notebooks:/home/jupyter/work/notebooks:rw
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GDAL_DRIVER_PATH=/opt/eopf-zarr/drivers
      - GDAL_DATA=/usr/share/gdal
      - PROJ_LIB=/usr/share/proj
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/lab"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
