name: eopf-zarr
channels:
  - conda-forge
dependencies:
  - python=3.13
  - gdal=3.10.*
  - cmake
  - ninja
  - zarr<3
  - dask
  - geopandas
  - rasterio
  - fiona
  - shapely
  - pyproj
  - netcdf4
  - h5py
  - scipy
  - matplotlib
  - cartopy
  - ipykernel
  - ipywidgets
  - jupyterlab
  - notebook
  - xarray
