/*********************************************************************
 *  EOPF‑Zarr GDAL driver — configuration options
 *
 *  This file is automatically generated by CMake from 
 *  eopfzarr_config.h.in. Do not edit directly!
 *********************************************************************/

#ifndef EOPFZARR_CONFIG_H
#define EOPFZARR_CONFIG_H

// Whether to use filename prefix for EOPF dataset identification
#define USE_FILENAME_PREFIX 0

// The filename prefix to identify EOPF datasets
#define EOPF_FILENAME_PREFIX ""

#endif // EOPFZARR_CONFIG_H
