# name: Build and Test
# 
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# 
# jobs:
#   build:
#     runs-on: ubuntu-latest
# 
#     env:
#       GDAL_DRIVER_PATH: ${{ github.workspace }}/build
#     
#     steps:
#     - uses: actions/checkout@v3
#     
#     - name: Install dependencies
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y libgdal-dev gdal-bin
#     
#     - name: Configure CMake
#       run: cmake -B ${{github.workspace}}/build
#     
#     - name: Build
#       run: cmake --build ${{github.workspace}}/build
#     
#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest -V  # Verbose output to see test details
