name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev cmake build-essential

    - name: Configure
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Test
      run: |
        # create dummy file with extension .eopf
        touch build/test.eopf

        # ensure GDAL looks in 'build' for gdal_EOPF.so
        export GDAL_DRIVER_PATH=$GITHUB_WORKSPACE/build

        cd build
        ctest --verbose
