name: Build and Test
on:
  push:
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev cmake build-essential

    - name: Configure
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Debug listing
      run: |
        echo "Contents of build/Debug:"
        ls $GITHUB_WORKSPACE/build/Debug

    - name: Test
      run: |
        export GDAL_DRIVER_PATH=$GITHUB_WORKSPACE/build/Debug
        cd build
        ctest --verbose
